MY_PATH := vendor/magisk
MAGISK_OUT := $(PRODUCT_OUT)/obj/MAGISK
MAGISKUNZIPPED := $(MAGISK_OUT)/magisk
MAGISKPOLICY := $(MY_PATH)/mpolicy $(MAGISKUNZIPPED)/magiskpolicy
MAT_SEPOLICY_BREAKER := export ANDROID_BUILD_TOP=$$(pwd) && $(MAGISKPOLICY)
MAT_SEPOLICY_EXTRADEP := $(MAGISKUNZIPPED)
